apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: humor-game-base
  namespace: humor-game

# Base resources - STARTING WITH ONLY WORKING RESOURCES
# This fixes the Missing health status by avoiding configuration conflicts
resources:
- configmap.yaml
- pvc.yaml
- postgres-init.yaml
- security-contexts.yaml

# We'll add these back gradually once health status is stable:
# - redis-deployment.yaml
# - redis-service.yaml
# - postgres-deployment.yaml
# - postgres-service.yaml
# - backend-hpa.yaml
# - frontend-hpa.yaml
# - frontend-deployment.yaml
# - frontend-service.yaml
# - backend-deployment.yaml
# - backend-service.yaml

# NO patches - keeping it simple to avoid conflicts
# NO common labels - this prevents conflicts with your working app

# Common annotations
commonAnnotations:
  gitops.argoproj.io/description: "Base configuration for Humor Game"
  gitops.argoproj.io/version: "1.0.0"

# No patches or transformations for now
# This ensures your working app stays exactly as is
