apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: humor-game-base
  namespace: humor-game

# Base resources - these are the foundation configurations
# They won't interfere with your working app initially
resources: []
# We'll add base resources here, but for now it's empty
# This prevents any interference with your working app

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: humor-game
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/component: game-app

# Common annotations
commonAnnotations:
  gitops.argoproj.io/description: "Base configuration for Humor Game"
  gitops.argoproj.io/version: "1.0.0"

# No patches or transformations for now
# This ensures your working app stays exactly as is
