apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: humor-game-base
  namespace: humor-game

# Base resources - BUILDING FOUNDATION FIRST
# Start with core infrastructure, then add dependent resources
resources:
- configmap.yaml
- pvc.yaml
- postgres-init.yaml
- security-contexts.yaml
- redis-deployment.yaml
- redis-service.yaml
- postgres-deployment.yaml
- postgres-service.yaml

# We'll add these in order to avoid dependency issues:
# 1. First: Core infrastructure (Redis, Postgres) ← ADDING NOW
# 2. Then: Application deployments (Backend, Frontend) 
# 3. Finally: Dependent resources (HPAs, Services)

# NO patches - keeping it simple to avoid conflicts
# NO common labels - this prevents conflicts with your working app

# Common annotations
commonAnnotations:
  gitops.argoproj.io/description: "Base configuration for Humor Game"
  gitops.argoproj.io/version: "1.0.0"

# No patches or transformations for now
# This ensures your working app stays exactly as is
