apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: humor-game
  labels:
    app.kubernetes.io/name: humor-game
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: database
spec:
  selector:
    app: postgres
    app.kubernetes.io/name: humor-game
    app.kubernetes.io/component: database
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
