apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/secrets.yaml
  - ../../base/postgres.yaml
  - ../../base/redis.yaml
  - ../../base/backend.yaml
  - ../../base/frontend.yaml
  - ../../base/ingress.yaml

# Optional: Override replicas for dev environment
patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
