apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: gitops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: gitops-demo
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-app
