apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: humor-game

resources:
  - ../../base

commonLabels:
  environment: dev

# Dev-specific patches
patchesStrategicMerge:
  - values.yaml
