apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: humor-game

resources:
  - ../../base

commonLabels:
  environment: dev

# Dev-specific configuration
# For now, we'll use the base resources without patches
# This demonstrates the GitOps workflow without complex patching
