apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-app
  namespace: argocd
  labels:
    purpose: demo
    environment: learning
spec:
  project: default
  source:
    repoURL: https://github.com/Osomudeya/DevOps-Home-Lab-2025.git
    targetRevision: home-lab
    path: gitops-demo/base
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
