apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml
  - base/humor-game-config.yaml
  - base/humor-game-secrets.yaml
  - base/postgres.yaml
  - base/redis.yaml
  - base/backend.yaml
  - base/frontend.yaml
  - base/ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: humor-game
